name: Deploy to Github Pages

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**/*.[mM][dD]"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Vue
        uses: xRealNeon/VuePagesAction@1.0.0
        with:
          username: "Weather-Vortex"
          reponame: "weather-vortex-client"
          token: ${{ secrets.PAGES_TOKEN }}
